# openai_api_key: "YOUR OPENAI KEY"
openai_api_key: ""

openai_key: "YOUR OPENAI API KEY"
tmdb_access_token: "YOUR TMDB ACCESS TOKEN"
spotipy_client_id: "YOUR SPOTIFY APPLICATION CLIENT ID"
spotipy_client_secret: "YOUR SPOTIFY APPLCIATION CLIENT SECRET"
spotipy_redirect_uri: "URL TO YOUR APPLICATION"
YOUR_SCENARIO_KEY: "YOUR SCENARIO KEY HERE"
YOUR_SCENARIO_SECRET_IF_ANY: "YOUR SCENARIO SECRET HERE"

#spotipy_client_id: ""
#spotipy_client_secret: ""
#spotipy_redirect_uri: "http://localhost/"

NOTION_KEY: ""
NOTION_PAGE_ID: ""
NOTION_VERSION: "2022-02-22"

UPCLICK_KEY: ""

discord_client_id: ""
discord_client_secret: ""
discord_redirect_uri: "http://localhost/"

google_token: ""
# trello_key: ""
# trello_token: ""
